insert into categoria (id, nombre) values (125,'Aceites');
insert into categoria (id, nombre) values (127,'Aceitunas');
insert into categoria (id, nombre) values (232,'Aderezos');
insert into categoria (id, nombre) values (129,'Alfajores');
insert into categoria (id, nombre) values (130,'Alimentos liquidos de soja y otros');
insert into categoria (id, nombre) values (131,'Alimentos para bebes');
insert into categoria (id, nombre) values (132,'Arroz saborizado');
insert into categoria (id, nombre) values (133,'Articulos para la limpieza de vajilla');
insert into categoria (id, nombre) values (134,'Avena');
insert into categoria (id, nombre) values (135,'Aves y huevos');
insert into categoria (id, nombre) values (228,'Barras de cereales');
insert into categoria (id, nombre) values (167,'Bebidas alcohólicas');
insert into categoria (id, nombre) values (136,'Bebidas con sabores frutales ');
insert into categoria (id, nombre) values (233,'Bebidas no alcohólicas');
insert into categoria (id, nombre) values (203,'Bishul yisrael');
insert into categoria (id, nombre) values (137,'Cacao en polvo y preparados para leche');
insert into categoria (id, nombre) values (138,'Cafes y sustitutos');
insert into categoria (id, nombre) values (229,'Caldos en Polvo');
insert into categoria (id, nombre) values (206,'Caramelos y pastillas');
insert into categoria (id, nombre) values (139,'Caviar');
insert into categoria (id, nombre) values (207,'Cereales');
insert into categoria (id, nombre) values (140,'Cerveza');
insert into categoria (id, nombre) values (144,'Chicles');
insert into categoria (id, nombre) values (145,'Chocolates');
insert into categoria (id, nombre) values (146,'Chocolates para taza');
insert into categoria (id, nombre) values (141,'Comida de aviones');
insert into categoria (id, nombre) values (142,'Cosmeticos y crema dental');
insert into categoria (id, nombre) values (212,'Crema láctea');
insert into categoria (id, nombre) values (143,'Crema no lactea y saborizante de cafe');
insert into categoria (id, nombre) values (147,'Dulce de batata, membrillo y más');
insert into categoria (id, nombre) values (213,'Dulce de leche');
insert into categoria (id, nombre) values (148,'Edulcorantes');
insert into categoria (id, nombre) values (231,'Encurtidos');
insert into categoria (id, nombre) values (149,'Ensaladas de frutas en lata');
insert into categoria (id, nombre) values (150,'Especias');
insert into categoria (id, nombre) values (151,'Fideos');
insert into categoria (id, nombre) values (152,'Flanes y postres');
insert into categoria (id, nombre) values (153,'Frutas de israel');
insert into categoria (id, nombre) values (154,'Frutas disecadas');
insert into categoria (id, nombre) values (155,'Frutas y verduras enlatadas');
insert into categoria (id, nombre) values (156,'Galletas de arroz');
insert into categoria (id, nombre) values (157,'Galletitas');
insert into categoria (id, nombre) values (158,'Gaseosas');
insert into categoria (id, nombre) values (159,'Gelatinas');
insert into categoria (id, nombre) values (214,'Golosinas');
insert into categoria (id, nombre) values (215,'Harinas y Premezclas');
insert into categoria (id, nombre) values (160,'Heladerias');
insert into categoria (id, nombre) values (161,'Higado');
insert into categoria (id, nombre) values (162,'Jugos de frutas');
insert into categoria (id, nombre) values (163,'Ketchup');
insert into categoria (id, nombre) values (164,'Leche');
insert into categoria (id, nombre) values (165,'Leche chocolatada');
insert into categoria (id, nombre) values (166,'Leche en polvo');
insert into categoria (id, nombre) values (238,'Legumbres');
insert into categoria (id, nombre) values (168,'Manteca');
insert into categoria (id, nombre) values (169,'Manteca y margarina');
insert into categoria (id, nombre) values (170,'Mayonesa');
insert into categoria (id, nombre) values (204,'Medicamentos');
insert into categoria (id, nombre) values (205,'Mermeladas');
insert into categoria (id, nombre) values (217,'Miel y Productos de la colmena');
insert into categoria (id, nombre) values (171,'Milanesas de soja');
insert into categoria (id, nombre) values (172,'Mostaza');
insert into categoria (id, nombre) values (216,'Palitos Helados ');
insert into categoria (id, nombre) values (173,'Pan');
insert into categoria (id, nombre) values (174,'Pan rallado y rebozadores');
insert into categoria (id, nombre) values (237,'Panadería y pastelería');
insert into categoria (id, nombre) values (175,'Papas fritas');
insert into categoria (id, nombre) values (176,'Papas pre-fritas');
insert into categoria (id, nombre) values (177,'Pasta de mani y sesamo, mani y chocolate');
insert into categoria (id, nombre) values (178,'Pastas frescas');
insert into categoria (id, nombre) values (180,'Pescado ahumado');
insert into categoria (id, nombre) values (179,'Pescados envasados');
insert into categoria (id, nombre) values (218,'Pescados Frescos');
insert into categoria (id, nombre) values (181,'Polenta');
insert into categoria (id, nombre) values (182,'Polvo para preparar flanes');
insert into categoria (id, nombre) values (183,'Polvo para preparar jugos');
insert into categoria (id, nombre) values (184,'Polvo para preparar postres');
insert into categoria (id, nombre) values (185,'Polvos para preparar tortas');
insert into categoria (id, nombre) values (236,'Productos aptos Celiacos');
insert into categoria (id, nombre) values (186,'Productos de copetin');
insert into categoria (id, nombre) values (187,'Productos de reposteria');
insert into categoria (id, nombre) values (188,'Productos naturistas y varios');
insert into categoria (id, nombre) values (189,'Pure de papa');
insert into categoria (id, nombre) values (190,'Quesos');
insert into categoria (id, nombre) values (191,'Rollos y bandejas de alumino y material de cocina');
insert into categoria (id, nombre) values (192,'Salsas');
insert into categoria (id, nombre) values (193,'Sidras y afines');
insert into categoria (id, nombre) values (194,'Surimi');
insert into categoria (id, nombre) values (195,'Sushi');
insert into categoria (id, nombre) values (196,'Te saborizado');
insert into categoria (id, nombre) values (197,'Tomates en lata, en tetrabrick, salsas y pure');
insert into categoria (id, nombre) values (198,'Turrones');
insert into categoria (id, nombre) values (199,'Verduras frescas y congeladas');
insert into categoria (id, nombre) values (200,'Vinagre');
insert into categoria (id, nombre) values (201,'Vinos');
insert into categoria (id, nombre) values (227,'Vitaminas y Nutrientes');
insert into categoria (id, nombre) values (230,'Yerba Mate');
insert into categoria (id, nombre) values (202,'Yogures');
